### PR TITLE
Program remembers IP from last use. (In case of accidental close), also made the window bigger

### PR DESCRIPTION
**Pull request by GreemDev**
Changes: 

- Window Enlarged to not make the text [half appear](https://i.imgur.com/YOpPaMF.png).
- Made the Program remember the last IP it was checking for, in case of accidental close.
More to come, such as an actual program pic and stuff.

### CODE REVIEW

**Comment by GreemDev** [comment]
@mikevb1 Hope you enjoy these changes! Also we have the same real name :^)

**Comment by sgtlaggy** [comment]
It seems you forgot to commit the icon.

As for remembering last IP, I was thinking maybe `%APPDATA%` or even registry instead of the current directory, to reduce clutter.

Tested the UI changes, everything is just extended vertically, where it seems you meant to extend horizontally to fix the text cutoff.

**Comment by GreemDev** [comment]
yeah, it's just extended vertically, but it's an actual circle rather than an oval.

I've no idea how to put anything in appdata. I've only ever used current dir or subdirs. I'll commit the icon, give me a second.

**Comment by GreemDev** [comment]
done

**Comment by sgtlaggy** [comment]
image

This is how they look for me.

Do you have anything special in your setup? High DPI display, display scaling, supersampling, etc? And are you on Windows 8, 8.1, or 10?

**Comment by GreemDev** [comment]
Nothing special about my display, and I am on Windows 10 Pro. This is what my application looks like: https://i.greem.me/40pld9fve3.png

**Comment by sgtlaggy** [comment]
I'm going to look into other solutions for the text cutoff, but I'll cherry-pick the last IP and icon changes.

**Comment by sgtlaggy** [comment]
Fixed the circle squishing with `Stretch="Uniform"`. As for the text, could you maybe try setting `VerticalContentAlignment="Top"` for the offending controls?

**Comment by GreemDev** [comment]
I just went to bed, lol. You like the icon and last IP changes?

**Comment by sgtlaggy** [comment]
Please try the latest release. I made some changes to the padding of that label and made the ellipse `Stretch="Uniform"`, let me know if it fixed the issues.

**Comment by GreemDev** [comment]
Will do, currently working on a Discord bot for a server I have with a few friends. Gimme a bit.

**Pull request closed without merging**
